server:
  port: 8080

spring:
  application:
    name: SpringBatchDemo

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:~/test
    #初始化脚本
    #在浏览器中开启控制台
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2
  sql:
    init:
      mode: always
      platform: h2
      schema-locations: classpath:db/schema.sql